/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AsideCategories: typeof import('./../src/components/AsideCategories.vue')['default']
    AsideWithBanners: typeof import('./../src/views/home/components/AsideWithBanners.vue')['default']
    Banner: typeof import('./../src/components/Banner.vue')['default']
    BlockTitle: typeof import('./../src/components/BlockTitle.vue')['default']
    Copyright: typeof import('./../src/components/footer/Copyright.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRate: typeof import('element-plus/es')['ElRate']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTag: typeof import('element-plus/es')['ElTag']
    FeedbackItem: typeof import('./../src/views/home/components/FeedbackItem.vue')['default']
    FeedbacksSlider: typeof import('./../src/views/home/components/FeedbacksSlider.vue')['default']
    FilterByBrand: typeof import('./../src/views/products/components/FilterByBrand.vue')['default']
    FilterByPrice: typeof import('./../src/views/products/components/FilterByPrice.vue')['default']
    FilterByRangePrice: typeof import('./../src/views/products/components/FilterByRangePrice.vue')['default']
    FilterByRating: typeof import('./../src/views/products/components/FilterByRating.vue')['default']
    FooterMenu: typeof import('./../src/components/footer/FooterMenu.vue')['default']
    GridProductCard: typeof import('./../src/components/products/GridProductCard.vue')['default']
    IconArrowRight: typeof import('~icons/icon/arrow-right')['default']
    IconCart: typeof import('~icons/icon/cart')['default']
    IconFilters: typeof import('~icons/icon/filters')['default']
    IconGridView: typeof import('~icons/icon/grid-view')['default']
    IconListView: typeof import('~icons/icon/list-view')['default']
    IconLogo: typeof import('~icons/icon/logo')['default']
    IconLogout: typeof import('~icons/icon/logout')['default']
    IconSearch: typeof import('~icons/icon/search')['default']
    IconUser: typeof import('~icons/icon/user')['default']
    IconUserCircle: typeof import('~icons/icon/user-circle')['default']
    ItemsPerPage: typeof import('./../src/views/products/components/ItemsPerPage.vue')['default']
    ListProductCard: typeof import('./../src/components/products/ListProductCard.vue')['default']
    Logo: typeof import('./../src/components/Logo.vue')['default']
    MiddleBar: typeof import('./../src/components/header/MiddleBar.vue')['default']
    MostPopularProducts: typeof import('./../src/views/home/components/MostPopularProducts.vue')['default']
    ProductContainer: typeof import('./../src/components/products/ProductContainer.vue')['default']
    ProductsByLastSearch: typeof import('./../src/views/home/components/ProductsByLastSearch.vue')['default']
    ProductsSkeleton: typeof import('./../src/components/skeletons/ProductsSkeleton.vue')['default']
    ProductViewsSwitch: typeof import('./../src/views/products/components/ProductViewsSwitch.vue')['default']
    ProfileForm: typeof import('./../src/views/profile/components/ProfileForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./../src/components/Search.vue')['default']
    TopBar: typeof import('./../src/components/header/TopBar.vue')['default']
    UserMenu: typeof import('./../src/components/UserMenu.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
