/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Copyright: typeof import('./../src/components/footer/Copyright.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    FooterMenu: typeof import('./../src/components/footer/FooterMenu.vue')['default']
    IconCart: typeof import('~icons/icon/cart')['default']
    IconLogo: typeof import('~icons/icon/logo')['default']
    IconLogout: typeof import('~icons/icon/logout')['default']
    IconSearch: typeof import('~icons/icon/search')['default']
    IconUser: typeof import('~icons/icon/user')['default']
    Logo: typeof import('./../src/components/Logo.vue')['default']
    MiddleBar: typeof import('./../src/components/header/MiddleBar.vue')['default']
    ProfileForm: typeof import('./../src/views/profile/components/ProfileForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./../src/components/Search.vue')['default']
    TopBar: typeof import('./../src/components/header/TopBar.vue')['default']
    UserMenu: typeof import('./../src/components/UserMenu.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
