/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Copyright: typeof import('./../src/components/footer/Copyright.vue')['default']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    FooterMenu: typeof import('./../src/components/footer/FooterMenu.vue')['default']
    IconCart: typeof import('~icons/icon/cart')['default']
    IconLogo: typeof import('~icons/icon/logo')['default']
    IconSearch: typeof import('~icons/icon/search')['default']
    IconUser: typeof import('~icons/icon/user')['default']
    Logo: typeof import('./../src/components/Logo.vue')['default']
    MiddleBar: typeof import('./../src/components/header/MiddleBar.vue')['default']
    NavBar: typeof import('./../src/components/header/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./../src/components/Search.vue')['default']
    TopBar: typeof import('./../src/components/header/TopBar.vue')['default']
    UserWithCart: typeof import('./../src/components/UserWithCart.vue')['default']
  }
}
